windows.yml: Uninstall mingw-w64-x86_64-libgccjit to resolve conflicts
Symptom was:
  [..]
  looking for conflicting packages...
  error: failed to prepare transaction (could not satisfy dependencies)
  :: installing mingw-w64-x86_64-gcc (11.2.0-5) breaks dependency 'mingw-w64-x86_64-gcc=11.2.0-4' required by mingw-w64-x86_64-libgccjit